package com.conan.gankmvvm.data.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.conan.gankmvvm.model.GankEntity;

import com.conan.gankmvvm.data.database.dao.GankEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankEntityDaoConfig;

    private final GankEntityDao gankEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankEntityDaoConfig = daoConfigMap.get(GankEntityDao.class).clone();
        gankEntityDaoConfig.initIdentityScope(type);

        gankEntityDao = new GankEntityDao(gankEntityDaoConfig, this);

        registerDao(GankEntity.class, gankEntityDao);
    }
    
    public void clear() {
        gankEntityDaoConfig.clearIdentityScope();
    }

    public GankEntityDao getGankEntityDao() {
        return gankEntityDao;
    }

}
